name: solana_wallet_sample
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.8
  collection: 1.18.0
  flutter_bloc: 8.1.6
  bloc_concurrency: ^0.2.0
  freezed_annotation: 2.4.4
  cached_network_image: ^3.2.2
  flutter_svg: 2.0.3
  http: 1.2.2
  rxdart: 0.28.0
  shared_preferences: 2.3.2
  ffi: 2.1.3
  protobuf: ^4.0.0
  fixnum: ^1.1.1
  drift: ^2.19.1+1
  sqlite3_flutter_libs: ^0.5.24
  path_provider: ^2.0.0
  path: ^1.9.0
  secure_vault:
    path: ./secure_vault

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.4.12
  flutter_lints: 4.0.0
  freezed: 2.5.7
  json_serializable: 6.8.0
  ffigen: 13.0.0
  drift_dev: ^2.19.1



flutter:
  uses-material-design: true

  assets:
    - assets/icons/

ffigen:
  name: TrustWalletCore
  description: Bindings to `gen/headers/**.h
  output:
    bindings: 'lib/ffigen_output/generated_bindings.dart'
  headers:
    entry-points:
      - 'gen/headers/**.h'